-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 14:13:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
  @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monitorasus
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema monitorasus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monitorasus` DEFAULT CHARACTER SET utf8;

USE monitorasus;

-- -----------------------------------------------------
-- Table `monitorasus`.`empresaexame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`empresaexame` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  `latitude` DECIMAL(10, 8) NOT NULL,
  `longitude` DECIMAL(10, 8) NOT NULL,
  `foneCelular` VARCHAR(15) NOT NULL,
  `foneFixo` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

USE `monitorasus`;

-- -----------------------------------------------------
-- Table `monitorasus`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`estado` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `CodigoUf` INT(11) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Uf` CHAR(2) NOT NULL,
  `Regiao` INT(11) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE = InnoDB AUTO_INCREMENT = 82 DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`municipio` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Codigo` INT(11) NOT NULL,
  `Nome` VARCHAR(255) NOT NULL,
  `Uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE = InnoDB AUTO_INCREMENT = 5571 DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`pessoa` (
  `idpessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL DEFAULT 'M',
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(100) NULL DEFAULT NULL,
  `latitude` DECIMAL(10, 8) NOT NULL,
  `longitude` DECIMAL(10, 8) NOT NULL,
  `foneCelular` VARCHAR(15) NOT NULL,
  `foneFixo` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `dataNascimento` DATE NOT NULL,
  `hipertenso` TINYINT(4) NOT NULL DEFAULT '0',
  `diabetes` TINYINT(4) NOT NULL DEFAULT '0',
  `obeso` TINYINT(4) NOT NULL DEFAULT '0',
  `cardiopatia` TINYINT(4) NOT NULL DEFAULT '0',
  `imunodeprimido` TINYINT(4) NOT NULL DEFAULT '0',
  `cancer` TINYINT(4) NOT NULL DEFAULT '0',
  `doencaRespiratoria` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idpessoa`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`virusbacteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`virusbacteria` (
  `idVirusBacteria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idVirusBacteria`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`exame` (
  `idExame` INT(11) NOT NULL AUTO_INCREMENT,
  `idVirusBacteria` INT(11) NOT NULL,
  `idPaciente` INT(11) NOT NULL,
  `idAgenteSaude` INT(11) NOT NULL,
  `dataExame` DATE NOT NULL,
  `dataInicioSintomas` DATE NOT NULL,
  `igG` ENUM('S', 'N', 'I') NOT NULL DEFAULT 'N',
  `igM` ENUM('S', 'N', 'I') NOT NULL DEFAULT 'N',
  `pcr` ENUM('S', 'N', 'I') NOT NULL DEFAULT 'N',
  `idEstado` INT(11) NOT NULL,
  `idMunicipio` INT(11) NULL,
  `idEmpresaSaude` INT NULL,
  PRIMARY KEY (`idExame`),
  INDEX `fk_exame_virusBacteria1_idx` (`idVirusBacteria` ASC) VISIBLE,
  INDEX `fk_exame_pessoa1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_exame_pessoa2_idx` (`idAgenteSaude` ASC) VISIBLE,
  INDEX `fk_exame_estado1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_exame_municipio1_idx` (`idMunicipio` ASC) VISIBLE,
  INDEX `fk_exame_empresasaude1_idx` (`idEmpresaSaude` ASC) VISIBLE,
  CONSTRAINT `fk_exame_estado1` FOREIGN KEY (`idEstado`) REFERENCES `monitorasus`.`estado` (`Id`),
  CONSTRAINT `fk_exame_municipio1` FOREIGN KEY (`idMunicipio`) REFERENCES `monitorasus`.`municipio` (`Id`),
  CONSTRAINT `fk_exame_pessoa1` FOREIGN KEY (`idPaciente`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_exame_pessoa2` FOREIGN KEY (`idAgenteSaude`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_exame_virusBacteria1` FOREIGN KEY (`idVirusBacteria`) REFERENCES `monitorasus`.`virusbacteria` (`idVirusBacteria`),
  CONSTRAINT `fk_exame_empresasaude1` FOREIGN KEY (`idEmpresaSaude`) REFERENCES `monitorasus`.`empresaexame` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`pessoatrabalhamunicipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`pessoatrabalhamunicipio` (
  `idPessoa` INT(11) NOT NULL,
  `idMunicipio` INT(11) NOT NULL,
  `ehResponsavel` TINYINT(4) NOT NULL DEFAULT '0',
  `ehSecretario` TINYINT(4) NOT NULL DEFAULT '0',
  `situacaoCadastro` ENUM('S', 'A', 'I') NOT NULL DEFAULT 'S',
  PRIMARY KEY (`idPessoa`, `idMunicipio`),
  INDEX `fk_pessoa_has_municipio_municipio1_idx` (`idMunicipio` ASC) VISIBLE,
  INDEX `fk_pessoa_has_municipio_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_municipio_municipio1` FOREIGN KEY (`idMunicipio`) REFERENCES `monitorasus`.`municipio` (`Id`),
  CONSTRAINT `fk_pessoa_has_municipio_pessoa1` FOREIGN KEY (`idPessoa`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`situacaopessoavirusbacteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`situacaopessoavirusbacteria` (
  `idVirusBacteria` INT(11) NOT NULL,
  `idpessoa` INT(11) NOT NULL,
  `ultimaSituacaoSaude` ENUM('P', 'N', 'A', 'I', 'C') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`idVirusBacteria`, `idpessoa`),
  INDEX `fk_virusBacteria_has_pessoa_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  INDEX `fk_virusBacteria_has_pessoa_virusBacteria1_idx` (`idVirusBacteria` ASC) VISIBLE,
  CONSTRAINT `fk_virusBacteria_has_pessoa_pessoa1` FOREIGN KEY (`idpessoa`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`),
  CONSTRAINT `fk_virusBacteria_has_pessoa_virusBacteria1` FOREIGN KEY (`idVirusBacteria`) REFERENCES `monitorasus`.`virusbacteria` (`idVirusBacteria`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tipoUsuario` TINYINT(4) NOT NULL,
  `idPessoa` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa1` FOREIGN KEY (`idPessoa`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `monitorasus`.`pessoatrabalhaestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monitorasus`.`pessoatrabalhaestado` (
  `idpessoa` INT(11) NOT NULL,
  `idEstado` INT(11) NOT NULL,
  `ehResponsavel` TINYINT(4) NOT NULL DEFAULT '0',
  `ehSecretario` TINYINT(4) NOT NULL DEFAULT '0',
  `situacaoCadastro` ENUM('S', 'A', 'I') NOT NULL DEFAULT 'S',
  `idEmpresaExame` INT NULL,
  PRIMARY KEY (`idpessoa`, `idEstado`),
  INDEX `fk_pessoa_has_estado_estado1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_pessoa_has_estado_pessoa1_idx` (`idpessoa` ASC) VISIBLE,
  INDEX `fk_pessoatrabalhaestado_empresaexame1_idx` (`idEmpresaExame` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_estado_pessoa1` FOREIGN KEY (`idpessoa`) REFERENCES `monitorasus`.`pessoa` (`idpessoa`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_estado_estado1` FOREIGN KEY (`idEstado`) REFERENCES `monitorasus`.`estado` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoatrabalhaestado_empresaexame1` FOREIGN KEY (`idEmpresaExame`) REFERENCES `monitorasus`.`empresaexame` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;